/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as indexRouteImport } from './routes/index'
import { Route as SubAppBIndexRouteImport } from './../node_modules/@tsvrm/sub-app-b/src/routes/index'
import { Route as SubAppAIndexRouteImport } from './sub-app-a/routes/index'
import { Route as SubAppBProductsRouteImport } from './../node_modules/@tsvrm/sub-app-b/src/routes/products'
import { Route as SubAppBLayoutRouteImport } from './../node_modules/@tsvrm/sub-app-b/src/routes/_layout'
import { Route as SubAppAProductsRouteImport } from './sub-app-a/routes/products'
import { Route as SubAppALayoutRouteImport } from './sub-app-a/routes/_layout'

const indexRoute = indexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SubAppBIndexRoute = SubAppBIndexRouteImport.update({
  id: '/sub-app-b/',
  path: '/sub-app-b/',
  getParentRoute: () => rootRouteImport,
} as any)
const SubAppAIndexRoute = SubAppAIndexRouteImport.update({
  id: '/sub-app-a/',
  path: '/sub-app-a/',
  getParentRoute: () => rootRouteImport,
} as any)
const SubAppBProductsRoute = SubAppBProductsRouteImport.update({
  id: '/sub-app-b/products',
  path: '/sub-app-b/products',
  getParentRoute: () => rootRouteImport,
} as any)
const SubAppBLayoutRoute = SubAppBLayoutRouteImport.update({
  id: '/sub-app-b/_layout',
  path: '/sub-app-b',
  getParentRoute: () => rootRouteImport,
} as any)
const SubAppAProductsRoute = SubAppAProductsRouteImport.update({
  id: '/sub-app-a/products',
  path: '/sub-app-a/products',
  getParentRoute: () => rootRouteImport,
} as any)
const SubAppALayoutRoute = SubAppALayoutRouteImport.update({
  id: '/sub-app-a/_layout',
  path: '/sub-app-a',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof indexRoute
  '/sub-app-a': typeof SubAppALayoutRoute
  '/sub-app-a/products': typeof SubAppAProductsRoute
  '/sub-app-b': typeof SubAppBLayoutRoute
  '/sub-app-b/products': typeof SubAppBProductsRoute
  '/sub-app-a/': typeof SubAppAIndexRoute
  '/sub-app-b/': typeof SubAppBIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof indexRoute
  '/sub-app-a': typeof SubAppAIndexRoute
  '/sub-app-a/products': typeof SubAppAProductsRoute
  '/sub-app-b': typeof SubAppBIndexRoute
  '/sub-app-b/products': typeof SubAppBProductsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof indexRoute
  '/sub-app-a/_layout': typeof SubAppALayoutRoute
  '/sub-app-a/products': typeof SubAppAProductsRoute
  '/sub-app-b/_layout': typeof SubAppBLayoutRoute
  '/sub-app-b/products': typeof SubAppBProductsRoute
  '/sub-app-a/': typeof SubAppAIndexRoute
  '/sub-app-b/': typeof SubAppBIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sub-app-a'
    | '/sub-app-a/products'
    | '/sub-app-b'
    | '/sub-app-b/products'
    | '/sub-app-a/'
    | '/sub-app-b/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sub-app-a'
    | '/sub-app-a/products'
    | '/sub-app-b'
    | '/sub-app-b/products'
  id:
    | '__root__'
    | '/'
    | '/sub-app-a/_layout'
    | '/sub-app-a/products'
    | '/sub-app-b/_layout'
    | '/sub-app-b/products'
    | '/sub-app-a/'
    | '/sub-app-b/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  indexRoute: typeof indexRoute
  SubAppALayoutRoute: typeof SubAppALayoutRoute
  SubAppAProductsRoute: typeof SubAppAProductsRoute
  SubAppBLayoutRoute: typeof SubAppBLayoutRoute
  SubAppBProductsRoute: typeof SubAppBProductsRoute
  SubAppAIndexRoute: typeof SubAppAIndexRoute
  SubAppBIndexRoute: typeof SubAppBIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof indexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sub-app-b/': {
      id: '/sub-app-b/'
      path: '/sub-app-b'
      fullPath: '/sub-app-b/'
      preLoaderRoute: typeof SubAppBIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sub-app-a/': {
      id: '/sub-app-a/'
      path: '/sub-app-a'
      fullPath: '/sub-app-a/'
      preLoaderRoute: typeof SubAppAIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sub-app-b/products': {
      id: '/sub-app-b/products'
      path: '/sub-app-b/products'
      fullPath: '/sub-app-b/products'
      preLoaderRoute: typeof SubAppBProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sub-app-b/_layout': {
      id: '/sub-app-b/_layout'
      path: '/sub-app-b'
      fullPath: '/sub-app-b'
      preLoaderRoute: typeof SubAppBLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sub-app-a/products': {
      id: '/sub-app-a/products'
      path: '/sub-app-a/products'
      fullPath: '/sub-app-a/products'
      preLoaderRoute: typeof SubAppAProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sub-app-a/_layout': {
      id: '/sub-app-a/_layout'
      path: '/sub-app-a'
      fullPath: '/sub-app-a'
      preLoaderRoute: typeof SubAppALayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  indexRoute: indexRoute,
  SubAppALayoutRoute: SubAppALayoutRoute,
  SubAppAProductsRoute: SubAppAProductsRoute,
  SubAppBLayoutRoute: SubAppBLayoutRoute,
  SubAppBProductsRoute: SubAppBProductsRoute,
  SubAppAIndexRoute: SubAppAIndexRoute,
  SubAppBIndexRoute: SubAppBIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
